# Generated by Django 5.0 on 2025-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
